# Generated by Django 4.0.1 on 2022-01-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('ean_code', models.TextField(unique=True, verbose_name='Código de barras')),
                ('valor_salud', models.FloatField(verbose_name='Porcentaje de salud')),
                ('valor_energetico', models.FloatField(verbose_name='Calorias')),
                ('foto', models.ImageField(upload_to='productos/', verbose_name='Imagen del producto')),
                ('nutrientes', models.TextField(verbose_name='Nutrientes (json)')),
                ('huella_ecologica', models.TextField(verbose_name='Huella (json)')),
                ('ingredientes', models.TextField(verbose_name='Ingredientes (json)')),
                ('co2_producido', models.FloatField(verbose_name='CO2 producido (gramos)')),
                ('origen', models.TextField(verbose_name='Origen del producto')),
                ('indice_reciclaje', models.FloatField(verbose_name='Indice de reciclaje')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre de la receta')),
                ('tiempo_preparacion', models.IntegerField(verbose_name='Tiempo de preparacion (minutos)')),
                ('tiempo_cocinado', models.IntegerField(verbose_name='Tiempo de cocinado (minutos)')),
                ('ingredientes', models.TextField(verbose_name='Ingredientes (json)')),
                ('cantidades', models.TextField(verbose_name='Cantidades de ingredientes (json)')),
                ('pasos', models.TextField(verbose_name='Pasos a seguir (json)')),
                ('num_comensales', models.IntegerField(verbose_name='Número de comensales')),
                ('dificultad', models.IntegerField(verbose_name='Dificultad (1-5)')),
                ('foto', models.ImageField(upload_to='recetas/', verbose_name='Foto de la receta')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
    ]
